apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Name }}-configmap
data:
  RUST_LOG: {{ .rust.logEnv }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Name }}
  labels:
    app.kubernetes.io/name: {{ .Name }}
    app.kubernetes.io/part-of: {{ .FullName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Name }} 
      app.kubernetes.io/instance: {{ .FullName }}
  template:
    metadata:
      #annotations:
      #  ad.datadoghq.com/{{ .Name }}.logs: ''
      labels:
        app.kubernetes.io/name: {{ .Name }} 
        app.kubernetes.io/instance: {{ .FullName }}
        app.kubernetes.io/part-of: {{ .FullName }}
    spec:
      containers:
      - name: {{ .Name }}
        image: "{{ .containers.image }}:{{ .containers.tag }}"
        imagePullPolicy: {{ .containers.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Name }}-configmap
        ports:
        - containerPort: {{ .service.targetPort }}
{{- if .containers.resources }}
        resources:
{{ toYaml .containers.resources | indent 10 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}
  labels:
    app.kubernetes.io/name: {{ .Name }}
    app.kubernetes.io/instance: {{ .FullName }}
    app.kubernetes.io/part-of: {{ .FullName }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .service.port }}
    targetPort: {{ .service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ .Name }}
    app.kubernetes.io/instance: {{ .FullName }}
---
{{ if .ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Name }}
  labels:
    app.kubernetes.io/name: {{ .Name }} 
    app.kubernetes.io/part-of: {{ .FullName }}
spec:
  rules:
  - host: {{ .ingress.tls.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Name }}
          servicePort: {{ .service.port }}
        path: /
  tls:
  - secretName: {{ .ingress.tls.secretName }}
    hosts:
    - {{ .ingress.tls.host }}
{{- end }}
